using System;
using System.Collections.Generic;

namespace MontfoortIT.Business.Security
{
    ///<summary>
    /// A user that is generated by code and not stored.
    /// 
    /// This class is also used by unit testing
    ///</summary>
    public class InMemoryUser:IUser
    {
        private static int _id = 1;

        /// <summary>
        /// The name of the user
        /// </summary>
        public string UserName { get; private set; }
        
        /// <summary>
        /// The id of the user in memory
        /// </summary>
        public int Id { get; private set; }

        public Guid GuidID { get; private set; }

        /// <summary>
        /// The email of the user in memory
        /// </summary>
        public string Email 
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); } 
        }

        public bool IsApproved
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        /// <summary>
        /// The contstructor
        /// </summary>
        /// <param name="userName"></param>
        public InMemoryUser(string userName) : this(userName, Guid.NewGuid())
        {
            
        }

        /// <summary>
        /// The contstructor
        /// </summary>
        /// <param name="userName"></param>
        public InMemoryUser(string userName, Guid guidId)
        {
            UserName = userName;
            Id = _id++;
            GuidID = guidId;
        }

        /// <summary>
        /// The constructor
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userName"></param>
        public InMemoryUser(int id, string userName) : this(id, userName, Guid.NewGuid())
        {
        }

        /// <summary>
        /// The constructor
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userName"></param>
        public InMemoryUser(int id, string userName, Guid guidId)
        {
            UserName = userName;
            Id = id;

            _id = Math.Max(_id, id + 1);
            GuidID = guidId;
        }

        /// <summary>
        /// Saves an inmemory user (not implemented)
        /// </summary>
        public void Save()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Returns the username
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return UserName;
        }


        
    }
}